# docker-compose.yml
version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: darkdot-elasticsearch
    restart: on-failure
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx1024m"
      MAX_MAP_COUNT: "64000"
      discovery.type: "single-node"
      cluster.name: "darkdot-cluster"
      node.name: "darkdot-node"
      http.port: "9200"
      http.cors.enabled: "true"
      http.cors.allow-credentials: "true"
      http.cors.allow-origin: "*"
      http.cors.allow-methods: "GET"
      http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization,Access-Control-Allow-Headers,Accept"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    network_mode: "host"

  postgres:
    image: postgres
    container_name: darkdot-postgres
    restart: on-failure
    environment:
      POSTGRES_DB: darkdot
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: 1986
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: "host"

## IPFS Cluster #################################
#################################################

  ipfs0:
    image: ipfs/go-ipfs:v0.5.1
    container_name: darkdot-ipfs0
    restart: on-failure
    ports:
      - "4001:4001"
      - "127.0.0.1:5001:5001"
      - "8080:8080"
    volumes:
      - ./ipfs-data/daemon/staging:/export
      - ./ipfs-data/daemon/data:/data/ipfs

  ipfs-cluster:
    image: ipfs/ipfs-cluster:latest
    container_name: darkdot-ipfs-cluster
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: "Darkdot Cluster"
      CLUSTER_SECRET: ${CLUSTER_SECRET} # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTERPEERS: '*' # Trust all peers in Cluster (initially)
      CLUSTER_RESTAPI_CORSALLOWEDORIGINS: '*'
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      - "127.0.0.1:9094:9094"
      # - "9096:9096"
    volumes:
      - ./ipfs-data/cluster:/data/ipfs-cluster

#################################################

  ipfs1:
    image: ipfs/go-ipfs:v0.5.1
    container_name: darkdot-ipfs1
    restart: on-failure
    volumes:
      - peer_staging:/export
      - peer_data:/data/ipfs

  ipfs-peer:
    image: ipfs/ipfs-cluster:latest
    container_name: darkdot-ipfs-peer
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: "Darkdot Peer"
      CLUSTER_SECRET: ${CLUSTER_SECRET}
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTERPEERS: '*'
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - peer_cluster:/data/ipfs-cluster

#################################################
#################################################

  offchain:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: dappforce/darkdot-offchain:latest
    container_name: darkdot-offchain
    depends_on:
      - postgres
      - elasticsearch
      - ipfs-cluster
    restart: on-failure
    environment:
      - NODE_ENV=production
    network_mode: "host"

volumes:
  es_data:
    driver: local
  postgres_data:
    driver: local
  peer_staging:
    driver: local
  peer_data:
    driver: local
  peer_cluster:
    driver: local
